[package]
name = "iced_style"
version = "0.5.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2021"
description = "The default set of styles of Iced"
license = "MIT"
repository = "https://github.com/iced-rs/iced"
documentation = "https://docs.rs/iced_style"
keywords = ["gui", "ui", "graphics", "interface", "widgets"]
categories = ["gui"]

[dependencies.iced_core]
version = "0.6"
path = "../core"
features = ["palette"]

[dependencies.palette]
version = "0.6"

[dependencies.once_cell]
version = "1.15"

[dependencies.cosmic-theme]
git = "https://github.com/pop-os/cosmic-theme.git"
branch = "master"
#path = "../../cosmic-theme"
optional = true
