[package]
name = "iced_native"
version = "0.6.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2021"
description = "A renderer-agnostic library for native GUIs"
license = "MIT"
repository = "https://github.com/iced-rs/iced"

[features]
default = ["wayland"]
wayland = ["sctk"]
debug = []
# COSMIC Theme
cosmic_theme = ["iced_style/cosmic_theme"]

[dependencies]
twox-hash = { version = "1.5", default-features = false }
unicode-segmentation = "1.6"
num-traits = "0.2"
sctk = { package = "smithay-client-toolkit", git = "https://github.com/Smithay/client-toolkit", optional = true }

[dependencies.iced_core]
version = "0.6"
path = "../core"

[dependencies.iced_futures]
version = "0.5"
path = "../futures"
features = ["thread-pool"]

[dependencies.iced_style]
version = "0.5"
path = "../style"
