[package]
name = "iced_renderer"
version = "0.1.0"
edition = "2021"

[features]
default = ["tiny-skia"]
wgpu = ["iced_wgpu"]
tiny-skia = ["iced_tiny_skia"]
image = ["iced_wgpu/image", "iced_tiny_skia/image"]
svg = ["iced_wgpu/svg", "iced_tiny_skia/svg"]
geometry = ["iced_graphics/geometry", "iced_wgpu?/geometry", "iced_tiny_skia?/geometry"]
tracing = ["iced_wgpu/tracing"]

[dependencies]
raw-window-handle = "0.5"
thiserror = "1"

[dependencies.iced_graphics]
version = "0.8"
path = "../graphics"

[dependencies.iced_wgpu]
version = "0.10"
path = "../wgpu"
optional = true

[dependencies.iced_tiny_skia]
version = "0.1"
path = "../tiny_skia"
optional = true
